#!/usr/bin/env python3
"""Terraform -> Ansible inventory generator (Handoff_Layer component C4).

Feature: terraform-ansible-handoff (Req 3.x, 7.x; design C4, Data Models,
Error Handling, Correctness Properties).

This is the middle layer that connects the Terraform provisioning layer to the
Ansible roles layer. It runs ``terraform output -json`` against exactly one
Terraform root, reads that root's generic ``inventory_hosts`` output, and renders
a deterministic Ansible YAML inventory grouped by ``service_role`` (primary) and
``project_slug`` (secondary), with ``ansible_host`` set to each host's computed
IPv4 address and ``ansible_user`` set to ``root`` (matching the bpg/proxmox
``initialization.user_account.keys`` root-account injection mechanism).

Design invariants honoured here:

* The handoff is one-directional and file-mediated (Req 7.1): the generator only
  ever runs ``terraform output -json`` in a root directory. It NEVER reads a
  ``.tfstate`` file directly and NEVER queries the Proxmox API.
* Determinism (Req 3.4, 7.2): the same ``inventory_hosts`` payload always renders
  byte-identical YAML (sorted group and host keys).
* No secrets (Req 3.5): only the allowlisted non-secret fields
  (``hostname``, ``ipv4_address``, ``service_role``, ``project_slug``, ``vmid``,
*   ``node_name``)
  are read; any other field on an input host object is ignored, so a
  secret-shaped extra field can never reach the rendered output.
* Null-``vmid`` tolerance (Req 3.3, Q3): ``vmid`` is optional; the hostvar is
  omitted when null/absent and carried through when non-null.
* Fail-closed (Req 3.6): on a non-zero ``terraform``, malformed JSON, absent /
  non-list / empty ``inventory_hosts``, or a host missing a required field, the
  generator writes NOTHING, prints an explanatory error to stderr, and exits
  non-zero. The inventory is rendered fully in memory and written exactly once
  (via a temp file + ``os.replace``) so a mid-render failure never leaves a
  partial or empty file.
* Single root per invocation (Req 7.1): one ``--root`` -> one inventory. There is
  no merge mode, preserving per-root Terraform state isolation by construction.

The pure core (:func:`render_inventory`) is free of subprocess/file side effects
so it is trivially unit- and property-testable; :func:`main` is the thin
arg-parsing / subprocess / file-IO wrapper.

Usage::

    generate_inventory.py --root infra/projects/svc-07-secrets-manager \\
        --out ansible/inventory/svc-07-secrets-manager.generated.yml

    # offline test seam (no terraform invoked):
    generate_inventory.py --from-json payload.json --out /tmp/x.generated.yml
    cat payload.json | generate_inventory.py --from-json -   # -> stdout
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from typing import Any

import yaml

# The ONLY fields the generator reads from an input host object. Anything else
# (e.g. an adversarial token/password/private_key) is ignored -> Property 2.
_ALLOWLISTED_FIELDS = ("hostname", "ipv4_address", "service_role", "project_slug", "vmid", "node_name")
# Fields that MUST be present and non-null for a host to be valid. vmid is
# intentionally excluded (nullable/optional per Q3).
_REQUIRED_FIELDS = ("hostname", "ipv4_address", "service_role", "project_slug")

_HEADER = (
    "# GENERATED by ansible/inventory/generate_inventory.py — DO NOT EDIT.\n"
    "# Source: terraform output -json (root: {root})\n"
    "# Regenerate after every `terraform apply`. Gitignored; contains no secret.\n"
)


class InventoryError(Exception):
    """Raised by the pure core on any invalid / fail-closed input.

    Carrying this as a single defined exception lets ``main`` translate any
    render-time problem into a non-zero exit with a stderr message and NO file
    written (Req 3.6).
    """


def _extract_hosts(tf_output_json: Any) -> list[dict]:
    """Pull the ``inventory_hosts`` value out of a ``terraform output -json`` dict.

    Fail-closed (Req 3.6): the payload must be a dict carrying an
    ``inventory_hosts`` output whose ``.value`` is a NON-EMPTY list. Anything
    else raises :class:`InventoryError`.
    """
    if not isinstance(tf_output_json, dict):
        raise InventoryError(
            "terraform output payload is not a JSON object "
            f"(got {type(tf_output_json).__name__})"
        )
    if "inventory_hosts" not in tf_output_json:
        raise InventoryError("no inventory_hosts output present in terraform output")

    entry = tf_output_json["inventory_hosts"]
    # terraform output -json wraps each output as { value, type, sensitive }.
    # Tolerate a bare list too (defensive), but the canonical shape has .value.
    if isinstance(entry, dict) and "value" in entry:
        value = entry["value"]
    else:
        value = entry

    if not isinstance(value, list):
        raise InventoryError(
            "inventory_hosts value is not a list "
            f"(got {type(value).__name__})"
        )
    if len(value) == 0:
        raise InventoryError("no inventory hosts (inventory_hosts is empty)")
    return value


def _host_var_block(host: dict) -> dict:
    """Build the allowlisted hostvars for one host. Never copies extra fields."""
    for field in _REQUIRED_FIELDS:
        if host.get(field) in (None, ""):
            raise InventoryError(
                f"host {host.get('hostname', '<unknown>')!r} is missing required "
                f"field {field!r}"
            )
    block: dict[str, Any] = {
        "ansible_host": host["ipv4_address"],
        "ansible_user": "root",
    }
    vmid = host.get("vmid")
    if vmid is not None:
        block["vmid"] = vmid
    # node_name: the Proxmox node hosting this guest — optional/nullable, same
    # treatment as vmid. Carried through so downstream roles that address a guest
    # by its Proxmox node + VMID (e.g. the sdn_gateway per-guest firewall path)
    # read it as an inventory fact rather than hardcoding a node name.
    node_name = host.get("node_name")
    if node_name is not None:
        block["node_name"] = node_name
    return block


def render_inventory(tf_output_json: dict, *, root: str = "<unspecified>") -> str:
    """Pure core: ``terraform output -json`` dict -> deterministic inventory YAML.

    Returns the YAML text (including the fixed comment header). Raises
    :class:`InventoryError` on any invalid / empty / malformed input. This
    function performs NO subprocess and NO file IO, so tests can call it
    directly with synthesized dicts.

    Grouping: each host appears under a group named for its ``service_role``
    (carrying the full hostvars) and under a group named for its
    ``project_slug`` (with empty hostvars ``{}`` — the design's Data Models
    shape). Group and host keys are sorted so the render is deterministic
    (Req 3.4, 7.2).
    """
    hosts = _extract_hosts(tf_output_json)

    service_groups: dict[str, dict] = {}
    project_groups: dict[str, dict] = {}

    for host in hosts:
        if not isinstance(host, dict):
            raise InventoryError(
                f"host entry is not an object (got {type(host).__name__})"
            )
        hostname = host.get("hostname")
        if hostname in (None, ""):
            raise InventoryError("a host entry is missing required field 'hostname'")

        hostvars = _host_var_block(host)  # validates required fields; allowlist only
        service_role = host["service_role"]
        project_slug = host["project_slug"]

        service_groups.setdefault(service_role, {})[hostname] = hostvars
        # project_slug group carries the host with empty hostvars (design shape).
        project_groups.setdefault(project_slug, {})[hostname] = {}

    # Merge into a single children map; a service_role and project_slug can never
    # legitimately be sorted into collision here because they are separate groups,
    # but if a service_role string equals a project_slug string the service group
    # (full hostvars) is authoritative and the project entry is merged in.
    children: dict[str, dict] = {}
    for group, hostmap in service_groups.items():
        children.setdefault(group, {"hosts": {}})["hosts"].update(hostmap)
    for group, hostmap in project_groups.items():
        dest = children.setdefault(group, {"hosts": {}})["hosts"]
        for h, hv in hostmap.items():
            # do not clobber an existing full hostvars block with {}
            dest.setdefault(h, hv)

    inventory = {"all": {"children": children}}

    body = yaml.safe_dump(
        inventory,
        sort_keys=True,
        default_flow_style=False,
    )
    return _HEADER.format(root=root) + body


def _terraform_output_json(root: str) -> dict:
    """Run ``terraform output -json`` in ``root`` and parse it. Fail-closed."""
    try:
        proc = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise InventoryError(
            f"could not run terraform in root {root!r}: {exc}"
        ) from exc
    if proc.returncode != 0:
        raise InventoryError(
            f"`terraform output -json` failed in root {root!r} "
            f"(exit {proc.returncode}): {proc.stderr.strip()}"
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise InventoryError(
            f"`terraform output -json` in root {root!r} produced malformed JSON: {exc}"
        ) from exc


def _load_from_json(source: str) -> dict:
    """Read a terraform-output-json payload from a file or stdin ('-')."""
    try:
        if source == "-":
            raw = sys.stdin.read()
        else:
            with open(source, "r", encoding="utf-8") as fh:
                raw = fh.read()
    except OSError as exc:
        raise InventoryError(f"could not read --from-json source {source!r}: {exc}") from exc
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise InventoryError(f"--from-json source {source!r} is malformed JSON: {exc}") from exc


def _default_out_path(root: str) -> str:
    """Derive the default output path from the root directory basename (Q2)."""
    basename = os.path.basename(os.path.normpath(root))
    return os.path.join("ansible", "inventory", f"{basename}.generated.yml")


def _atomic_write(path: str, text: str) -> None:
    """Write ``text`` to ``path`` atomically (temp file + os.replace)."""
    directory = os.path.dirname(os.path.abspath(path))
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".inv-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def main(argv: list[str] | None = None) -> int:
    """Thin CLI wrapper: parse args, obtain output JSON, render, write once.

    Returns a process exit code (0 success, non-zero fail-closed). On any
    failure NOTHING is written to the output path.
    """
    parser = argparse.ArgumentParser(
        prog="generate_inventory.py",
        description="Render an Ansible inventory from a Terraform root's "
        "`terraform output -json` (Handoff_Layer C4).",
    )
    parser.add_argument(
        "--root",
        help="Terraform root directory; `terraform output -json` is run IN it. "
        "Required unless --from-json is given.",
    )
    parser.add_argument(
        "--out",
        help="Output inventory path. Default: ansible/inventory/"
        "<basename-of-root>.generated.yml. If omitted with --from-json (and no "
        "--root), the inventory is written to stdout.",
    )
    parser.add_argument(
        "--from-json",
        dest="from_json",
        metavar="FILE|-",
        help="Read the terraform-output-json payload from a file (or stdin '-') "
        "INSTEAD of invoking terraform. Offline test seam.",
    )
    args = parser.parse_args(argv)

    if not args.root and not args.from_json:
        print("error: one of --root or --from-json is required", file=sys.stderr)
        return 2

    root_label = args.root if args.root else "<from-json>"

    try:
        if args.from_json:
            payload = _load_from_json(args.from_json)
        else:
            payload = _terraform_output_json(args.root)
        rendered = render_inventory(payload, root=root_label)
    except InventoryError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    # Determine destination.
    if args.out:
        out_path: str | None = args.out
    elif args.root:
        out_path = _default_out_path(args.root)
    else:
        out_path = None  # --from-json only, no --out -> stdout

    if out_path is None:
        sys.stdout.write(rendered)
        return 0

    try:
        _atomic_write(out_path, rendered)
    except OSError as exc:
        print(f"error: could not write inventory to {out_path!r}: {exc}", file=sys.stderr)
        return 1

    print(f"wrote inventory: {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
